services:
  efdb:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1338
    volumes:
      - pgdata:/var/lib/postgresql/ef-data
  mytodoapi:
    environment:
      DOTNET_ENVIRONMENT: EFTest
      CONNECTIONSTRINGS__POSTGRES: "Server=efdb;Host=efdb;Port=5432;User ID=admin;Password=password1338;Database=postgres;"
    build:
      context: ./MyTodoApi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - efdb

volumes:
  pgdata:
